// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users_feeds.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUserFeed = `-- name: CreateUserFeed :one
INSERT INTO users_feeds (id, created_at, updated_at, feed_id, user_id)
VALUES ($1, NOW(), NOW(), $2, $3)
RETURNING id, created_at, updated_at, user_id, feed_id
`

type CreateUserFeedParams struct {
	ID     uuid.UUID
	FeedID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) CreateUserFeed(ctx context.Context, arg CreateUserFeedParams) (UsersFeed, error) {
	row := q.db.QueryRowContext(ctx, createUserFeed, arg.ID, arg.FeedID, arg.UserID)
	var i UsersFeed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}

const deleteUserFeed = `-- name: DeleteUserFeed :exec
DELETE
FROM users_feeds
WHERE id = $1
AND user_id = $2
`

type DeleteUserFeedParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteUserFeed(ctx context.Context, arg DeleteUserFeedParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserFeed, arg.ID, arg.UserID)
	return err
}

const readUserFeeds = `-- name: ReadUserFeeds :many
SELECT id, created_at, updated_at, user_id, feed_id
FROM users_feeds
WHERE user_id = $1
`

func (q *Queries) ReadUserFeeds(ctx context.Context, userID uuid.UUID) ([]UsersFeed, error) {
	rows, err := q.db.QueryContext(ctx, readUserFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersFeed
	for rows.Next() {
		var i UsersFeed
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
